Task 1- UX Task/Task-1_UX_design.txt
Issue: 1
Designed a Flowchart which describes the idea for building an app(Campus OLX) for selling or buying things.
=> Completed task-1 UX design

Task 1- UX Task/anshgeez31.txt
=> Task 1 completed

SST 1- Understanding Basics/anshgeez31.txt
=> Completed SST1: Understanding basics

SST 1- Understanding Basics/ananyaa07.txt
Issue: 5
I have mentioned the problems and suggestions to improve the designs which were provided.
=> completed-task

SST 1- Understanding Basics/zitsav.txt
=> Side Task 1 Completed

SST 1- Understanding Basics/aasthaaaa7.txt
=> small side task

SST 1- Understanding Basics/RayLikesAnime.txt
=> Small SIdetask 1

Task 1- UX Task/Siddhant_Agarwal.txt
=> Added Siddhant_Agarwal.txt to Task 1- UX Task

SST 1- Understanding Basics/hargunkaur286.txt
Issue: Small side task-1
Created a google doc and pointed out the possible errors in the UI and the UX
=> small side task-1

Task 1- UX Task/ananyaa07.txt
Issue: 2
I have designed the userflow for CampusOlx
=> task-completed

SST 1- Understanding Basics/prathambhatia86.txt
=> issue :5 side task completed

Task 1- UX Task/task1_ux_riddhi.txt
=> new commit

Task 2- Hero Section Design/SanyamAgrawal07.txt
=> Task 2 done

SST 2- Copying Main Screens/aasthaaaa7.txt
=> small side task 2

Task 2- Hero Section Design/Siddhant-Agarwal4583.txt
=> Siddhant-Agarwal4583 completed Task 2- Hero Section Design

SST 2- Copying Main Screens/AkshayW1.txt.txt, Task 2- Hero Section Design/akshayw1.txt
=> Hero Section Link Added

SST 2- Copying Main Screens/akshayw1git.txt
=> Figma Changes done

Task 2- Hero Section Design/ananyaa07.txt
Issue: 31
I have created the hero section for Campus Olx
=> hero-section

SST 3- OpenCode T-shirt Design/Vishesh-Vijay.txt, Task 2- Hero Section Design/Vishesh-Vijay.txt
=> Hero Section Design completed

Task 2- Hero Section Design/aasthaaaa7.txt
=> hero section

Task 2- Hero Section Design/Vishesh-Vijay.txt
=> Hero Section Design done

Task 2- Hero Section Design/anshgeez31.txt
=> Hero Section designed

Task 2- Hero Section Design/shashi_hero.txt
issue: 31
added a figma file in .txt format , for the hero section page required.
=> Hero section added

Frontend-Forum Collab Task/aasthaaaa7.txt, SST 3- OpenCode T-shirt Design/aasthaaaa7.txt
=> T shirt design

SST 3- OpenCode T-shirt Design/ananyaa07.txt
=> tshirt-design

SST 3- OpenCode T-shirt Design/SanyamAgrawal07.txt
=> SST 3 done

Task 3- CampusOLX LOGO Design/ananyaa07.txt
=> logo-design

Task 3- CampusOLX LOGO Design/ananyaa07.txt, Task 4- Website Footer Design/ananyaa07.txt
=> Footer design

Task 4- Website Footer Design/SanyamAgrawal07.txt
=> Footer Design Task

Task 4- Website Footer Design/Koshal7.txt
=> Task 4 Footer

Task 4- Website Footer Design/JahnaviGadde.txt
=> Footer for website

Design Rep #1/aasthaaaa7.txt
=> design reps

SST 2- Copying Main Screens/JahnaviGadde.txt
=> Design Reps #1

Design Rep #1/SanyamAgrawal07.txt
=> Design reps 1

Design Rep #1/bhumika-kalaru.txt
=> Design Rep #1

Design Rep #2/JahnaviGadde.txt
=> Design Reps #2

Design Rep #2/aasthaaaa7.txt
=> design reps 2

Design Rep #2/JackofAllCodez.txt
=> Design Rep #2

Design Rep #2/SanyamAgrawal07.txt
=> Design Rep 2

Design Rep #3/JackofAllCodez.txt
=> Design Rep-3 done

Design Rep #2/Koshal7.txt
=> Design Rep

fun task- Play the game/anshgeez31.txt
=> Fun Task Done

SST 4- LOGO design for LOST AND FOUND/SanyamAgrawal07.txt
=> Lost and found logo

Design Rep #2/shashiii.txt
=> Task done design rep 2

Design Rep #2/thedivineaurora.txt
=> fresher design task-2

Design Rep #3/aasthaaaa7.txt
=> design reps 3

Design Rep #3/SanyamAgrawal07.txt
=> Design rep 3

Task 6- Testimonials section/ananyaa07.txt
=> testimonials

Task 8- Last task/ananyaa07.txt
=> final task

Task 7- How it works section/ananyaa07.txt
=> How it works design

SST 6- Credit Card Design/aasthaaaa7.txt, Task 6- Testimonials section/aasthaaaa7.txt
=> Credit Card

Task 6- Testimonials section/aasthaaaa7.txt
Issue: 140
Testimonial Section
=> testimonial
